<?php
function cmwn_feed_vids(){
  return array(6);
}

function cmwn_feed_admin(){
  $form = array();
  
  $vocabularies  = cmwn_feed_vids();
  
  //get options for taxonomy terms for categories vocabulary
  $options = array();
  
  //vocabularies to collect sort weights for
  
  foreach($vocabularies as $vid){
    $terms = taxonomy_get_tree($vid);//5 is vid for feed categories
    
    if(is_array($terms)){
      
      $result = db_query("SELECT tid, weight FROM {cmwn_feed_term_weight} cftw", $type);
  
      $weights = array();
  
      while ($row = db_fetch_object($result)) {
        $weights[$row->tid] = $row->weight;
      }
      //dsm($weights);
      
      foreach($terms as $term){
        $form['cmwn_feed_weight_' . $term->tid] = array(
          '#type' => 'textfield',
          '#title' => $term->name . ' ' . t('Weight'),
          '#default_value' => $weights[$term->tid]?$weights[$term->tid]:1,
          '#size' => 3,
          '#maxlength' => 3,
          '#description' => t("Specify the weight of feed items by category here. This will affect how items appear in user friend feeds."),
          '#required' => TRUE,
        );      
      }
    }    
  }

  
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('submit'),
  );
  
  $form['#submit'][] = 'cmwn_feed_settings_submit';
  $form['#validate'][] = 'cmwn_feed_settings_validate';

  return ($form);  
}

function cmwn_feed_settings_validate($form, &$form_state){

  $vocabularies  = cmwn_feed_vids();  
  
  foreach($vocabularies as $vid){
    $terms = taxonomy_get_tree($vid);
    if(is_array($terms)){  
      foreach($terms as $term){  
        if(!is_numeric($form_state['values']['cmwn_feed_weight_' . $term->tid]) && $form_state['values']['cmwn_feed_weight_' . $term->tid] != '0'){
          form_set_error('cmwn_feed_weight_' . $term->tid,t('This must be a non-zero integer or decimal number.'));
        }
      }
    }    
  }
  
}

function cmwn_feed_settings_submit($form, &$form_state){
  $vocabularies  = cmwn_feed_vids();  
  
  foreach($vocabularies as $vid){
    $terms = taxonomy_get_tree($vid);
    if(is_array($terms)){
      //dsm($form_state);
      $result = db_query("SELECT tid, weight FROM {cmwn_feed_term_weight} cftw", $type);
      $weights = array();
      while ($row = db_fetch_object($result)) {
        $weights[$row->tid] = (float)$row->weight;
      }    

      foreach($terms as $term){
        $weight = false;
        @$weight = $weights[$term->tid];

        if($weight){
          $object = array();
          $object['tid'] = $term->tid;
          $object['weight']  = $form_state['values']['cmwn_feed_weight_' . $term->tid];
          $res = drupal_write_record('cmwn_feed_term_weight', $object, array('tid'));
        }else{
          $object = array();
          $object['tid'] = $term->tid;
          $object['weight']  = $form_state['values']['cmwn_feed_weight_' . $term->tid];        
          $res = drupal_write_record('cmwn_feed_term_weight', $object);  
        }
      }
    }
  }
}


function cmwn_feed_init() {
  
}

function cmwn_feed_form_alter(&$form, &$form_state, $form_id) {
  switch ($form_id) {
    case 'user_profile_form':
      
      break;
  }
}

function cmwn_feed_menu() {
  
  $items['cmwn_feed/friend'] = array(
    'page callback' => 'cmwn_friend_feed',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  
  $items['admin/settings/cmwn_feed'] = array(
    'title' => 'Administer Feed Settings',
    'description' => 'Description of your On this date settings page',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('cmwn_feed_admin'),
    'access arguments' => array('administer cmwn_feed settings'),
    'type' => MENU_NORMAL_ITEM,
   );  
   
  return $items;
}

//TODO: This has no security, no user checks etc.
function cmwn_friend_feed($uid = 0, $page = 0) {//ganked/modified from feed.inc in v2 profile
    
		$items = array();

		$user = user_load($uid);

		if (!$user) return $items;

		$query = "SELECT n.nid, n.uid, td.tid, ctf.field_excerpt_value AS excerpt FROM {node} AS n JOIN {term_node} AS tn ON n.nid = tn.nid JOIN {term_data} AS td ON tn.tid = td.tid and td.vid = 5 JOIN {content_type_feed} AS ctf ON n.nid = ctf.nid JOIN {cmwn_feed_term_weight} cftw on cftw.tid = (select tdd.tid from {term_data} tdd JOIN {term_node} tnn on tnn.tid = tdd.tid AND tdd.vid = 6 where tnn.nid = n.nid limit 1) WHERE n.type = 'feed' AND n.status = 1 ORDER BY (cftw.weight * n.created) DESC"; //5 is feed category, 6 is vid of feed type (post on own, post on friends, comment on own, commend on friend)

    $count_query = "SELECT COUNT(*) FROM (" . $query . ") AS count_query";

		$results = pager_query($query, 13, 0, $count_query);

		while ($result = db_fetch_object($results)) {
			$item = new stdClass();
			$item->excerpt = $result->excerpt;
			$item->nid = $result->nid;
			$item->tid = $result->tid;
			$item->uid = $result->uid;
  		$item->href = url('node/' . $item->nid);
  		$item->src = v2_profiles_avatars_query($item->uid);			
			$items[] = $item;
		}

		?>
		
    <?php foreach ($items as $item) { ?>
      <?php if($item->tid == 88):?>
      	<div class="item">
      		<span class="image">
      			<img height="42" src="<?php print $item->src; ?>" width="42" />
      		</span>
      		<?php
      			$_excerpt = $item->excerpt;
      			$_excerpt = str_replace('/user/'.$user->uid, '/user', $_excerpt);
      			$_excerpt = preg_replace('/("\/user\/)([0-9]+)(")/i', '/user/'.$user->uid.'/friends/$2/', $_excerpt);
      		?>
      		<span class="message">
      			<?php print $_excerpt; ?>
      		</span>
      	</div>
      	<?php endif; ?>
    <?php } ?>		
    <?php
      print theme('pager', NULL, 10, 0);
      exit;
}

