<?php

function cmwn_word_filter_menu() {
  $items = array();
  $items['admin/settings/cmwn/wordfilter'] = array(
    'title' => t('Word Filter Settings'),
    'description' => t(''),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('cmwn_word_filter_admin_settings'),
    'access arguments' => array('administer site configuration'),
  );
  return $items;
}

function cmwn_word_filter_admin_settings() {
  $form = array(
    'cmwn_word_filter_filtered_words' => array(
      '#type' => 'textarea',
      '#title' => 'Filtered Words',
      '#default_value' => variable_get('cmwn_word_filter_filtered_words', ''),
      '#rows' => 20,
      '#description' => t('Separate words by newline. All words are wrapped in word boundary control characters in a RegEx.')
    )
  );
  return system_settings_form($form);
}

function cmwn_word_filter_rules_condition_info() {
  return array(
    'cmwn_word_filter_condition_inappropriate_content' => array(
      'label' => t('Node contains inappropriate content'),
      'arguments' => array(
        'node' => array('type' => 'node', 'label' => t('Node to test'))
      ),
      'module' => 'CMWN',
    ),
  );
}

function cmwn_word_filter_rules_action_info() {
  return array(
    'cmwn_word_filter_action_inappropriate_content_flag_note' => array(
      'label' => t('Add Flag Note'),
      'arguments' => array(
        'flag' => array(
          'type' => 'flag',
          'label' => t('Flag'),
        ),
        'node' => array('type' => 'node', 'label' => t('Node to test'))
      ),
      'module' => 'Flag',
    ),
  );
}

function cmwn_word_filter_condition_inappropriate_content($node) {
  static $filter_expressions = false;
  if (!$filter_expressions) {
    $filter_expressions = explode("\n", variable_get('cmwn_word_filter_filtered_words', ''));
    array_walk($filter_expressions, '_cmwn_word_filter_array_walker');
  }
  $found = false;
  $matches = array();
  if (preg_match_all('/\b('.join($filter_expressions, '|').')\b/i', $node->title.' '.$node->body, $matches) > 0) {
    $found = true;
  }
  return $found;
}

function cmwn_word_filter_action_inappropriate_content_flag_note($flag, $node) {
  $note = 'Flagged by automatic word filter.';
  $flag->flag_note = $note;
  $account = user_load(1);
  $result = $flag->flag('flag', $node->nid, $account, true);
  if (!empty($result)) {
    $userflag = flag_get_user_flags($flag->content_type,
        $node->nid, $account->uid);
    $record = $userflag[$flag->name];
    //
    // Now uid = 0 if is a global flag. Anyway we want to store the note author so we change it
    //
    $record->uid  = $account->uid;
    $record->note = $note;
    flag_note_insert_note($record);
  }
}

function _cmwn_word_filter_array_walker(&$value, $key) {
  $value = trim($value);
}