<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Untitled Document</title>
</head>

<body>

<table cellpadding="0" cellspacing="0" border="0" width="100%">
  <tr>
    <td>

      <table cellpadding="0" cellspacing="0" border="0" width="657" align="center">
        <tr>
          <td>

<table cellpadding="0" cellspacing="0" border="0">
  <tr>
    <td>
<img src="<?php echo $url; ?>email/head.gif" width="657" height="225" alt="Change My World Now: A better world for kids by kids" border="0" style="display:block;">
    </td>
  </tr>
  </table>



<table cellpadding="0" cellspacing="0" border="0">
  <tr>

    <td width="85" valign="top"><img src="<?php echo $url; ?>email/shadow-top-left.gif" width="85" height="300" alt="" border="0" style="display:block;"></td>
    <td width="28" style="background:#00bbff;"></td>
    <td width="40"></td>
    <td width="426">

<img src="<?php echo $url; ?>email/spacer.gif" width="15" height="30" alt="" border="0" style="display:block;">
<img src="<?php echo $url; ?>email/hello-again.png" width="240" height="50" alt="" border="0" style="display:block;">
<img src="<?php echo $url; ?>email/spacer.gif" width="15" height="15" alt="" border="0" style="display:block;">

<p style="font-family:Arial, Helvetica, sans-serif; font-size:14px; line-height:17px; color:#3b3b3b;">
  <strong>Dear Parent or Guardian,</strong>
</p>

<p style="font-family:Arial, Helvetica, sans-serif; font-size:14px; line-height:17px; color:#3b3b3b;">
  Another one of your children has created a free profile on ChangeMyWorldNow.com, the safe social network that inspires and empowers kids to make the world a better place.
</p>

<p style="font-family:Arial, Helvetica, sans-serif; font-size:14px; line-height:17px; color:#3b3b3b;">
  Until you activate your child's account, they will only have limited access to the site's features.
  To activate your child's account, please create a profile by following the link below.
  From here you will have parental controls and be able to customize your child's experience on the site.
</p>

<p style="text-align:center;">
  <img src="<?php echo $url; ?>email/use-the-following-token.png" width="269" height="57" alt="Log in and use the following token to add your child:" border="0">
</p>

<p style="text-align:center;">
  <?= $parent_registration_token; ?>
</p>

<p style="text-align:center;">
  <a href="<?= $url; ?>user/login?cptoken=<?= $parent_registration_token; ?>" target="_blank"><img src="<?php echo $url; ?>email/login-and-add-your-child.png" width="264" height="62" alt="Login And Add Your Child" border="0"></a>
</p>

<p style="font-family:Arial, Helvetica, sans-serif; font-size:14px; line-height:17px; color:#3b3b3b;">
  We’re excited to continue changing the world with you and your family.
</p>

<p style="font-family:Arial, Helvetica, sans-serif; font-size:14px; line-height:17px; color:#3b3b3b;">
  <strong>Sincerely,</strong>
</p>

    </td>
    <td width="40"></td>
    <td width="29" style="background:#00bbff;"></td>
    <td width="9" valign="top"><img src="<?php echo $url; ?>email/shadow-top-right.gif" width="9" height="300" alt="" border="0" style="display:block;"></td>
  </tr>
</table>



<table cellpadding="0" cellspacing="0" border="0">
  <tr>
    <td width="85"></td>
    <td width="28" style="background:#00bbff;"></td>
    <td width="10"></td>
    <td width="456">

<img src="<?php echo $url; ?>email/signature.gif" width="149" height="68" alt="" border="0" style="display:block;">

    </td>
    <td width="40"></td>
    <td width="29" style="background:#00bbff;"></td>
    <td width="9"></td>
  </tr>
</table>

<table cellpadding="0" cellspacing="0" border="0">
  <tr>
    <td width="85"></td>
    <td width="28" style="background:#00bbff;"></td>
    <td width="40"></td>
    <td width="426">

<p style="font-family:Arial, Helvetica, sans-serif; font-size:14px; line-height:17px; color:#3b3b3b;">
<strong>Gina Otto</strong><br />
Founder of Change My World Now<br />
and Author of Cassandra's Angel</p>
<br /><br />
    </td>
    <td width="40"></td>
    <td width="29" style="background:#00bbff;"></td>
    <td width="9"></td>
  </tr>
</table>

<table cellpadding="0" cellspacing="0" border="0">
  <tr>
    <td><img src="<?php echo $url; ?>email/bottom.gif" width="657" height="7" alt="" border="0" style="display:block;">
    </td>
  </tr>
</table>


<table cellpadding="0" cellspacing="0" border="0">
  <tr>
    <td width="113"><img src="<?php echo $url; ?>email/bottom-left.gif" width="113" height="318" alt="" border="0" style="display:block;"></td>
    <td width="309" style="background:#00bbff;" valign="bottom">



<table cellpadding="0" cellspacing="0" border="0">
  <tr>
    <td height="309" valign="top">

<img src="<?php echo $url; ?>email/spacer.gif" width="25" height="25" alt="" border="0" style="display:block;">

<p style="margin-top:0px;"><img src="<?php echo $url; ?>email/img-lets-make-social-networking.gif" width="299" height="84" alt="Let's Make Social Networking More Socially Conscious!" border="0" style="display:block;"></p>

<p><img src="<?php echo $url; ?>email/img-partners.gif" width="309" height="71" alt="Partners" border="0" style="display:block;"></p>


<p style="font-family:Arial, Helvetica, sans-serif; font-size:10px; height:14px; color:#FFF;">
<em>Change My World Now</em> is dedicated to fostering creativity and learning in all online experiences. We are committed to ensuring the safety and well-being of children of all ages. To view the  complete privacy policy and terms and conditions of participation, <a href="<?php echo $url; ?>/legalprivacy" target="_blank" style="color:#FFF;">click here</a>.</p>


    </td>
  </tr>
  <tr>
    <td height="9"><img src="<?php echo $url; ?>email/bottom-shadow.gif" width="309" height="9" alt="" border="0" style="display:block;"></td>
  </tr>
</table>


    </td>
    <td width="235"><img src="<?php echo $url; ?>email/img-child.gif" width="235" height="318" alt="" border="0" style="display:block;"></td>
  </tr>
</table>

          </td>
        </tr>
      </table>

    </td>
  </tr>
</table>


</body>
</html>